module.exports = {
  SERVER_URL: 'http://localhost:5000',
  PORT: 5000,

  MIN_HANDLE_LENGTH: 1,
  MAX_HANDLE_LENGTH: 128,

  MIN_CHANNEL_NAME_LENGTH: 1,
  MAX_CHANNEL_NAME_LENGTH: 128,

  MIN_CHANNEL_DESCRIPTION_LENGTH: 1,
  MAX_CHANNEL_DESCRIPTION_LENGTH: 512,

  MAX_MESSAGE_LENGTH: 1028,

  MIN_USERNAME_LENGTH: 1,
  MAX_USERNAME_LENGTH: 32,

  MIN_PASSWORD_LENGTH: 6,
  MAX_PASSWORD_LENGTH: 128,
}
